---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/accounts":
    get:
      summary: list accounts
      tags:
      - Accounts
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                  - id
                  - balance
                  - created_at
                  - updated_at
                  - user_id
                  properties:
                    id:
                      type: number
                    balance:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    user_id:
                      type: number
                    user:
                      type: object
                      required:
                      - id
                      - first_name
                      - last_name
                      - created_at
                      - updated_at
                      properties:
                        id:
                          type: number
                        first_name:
                          type: string
                        last_name:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
    post:
      summary: create account
      tags:
      - Accounts
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - balance
                - created_at
                - updated_at
                - user_id
                properties:
                  id:
                    type: number
                  balance:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  user_id:
                    type: number
                  user:
                    type: object
                    required:
                    - id
                    - first_name
                    - last_name
                    - created_at
                    - updated_at
                    properties:
                      id:
                        type: number
                      first_name:
                        type: string
                      last_name:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: object
                  required:
                  - user_id
                  properties:
                    user_id:
                      type: number
  "/accounts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show account
      tags:
      - Accounts
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - balance
                - created_at
                - updated_at
                - user_id
                properties:
                  id:
                    type: number
                  balance:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  user_id:
                    type: number
                  user:
                    type: object
                    required:
                    - id
                    - first_name
                    - last_name
                    - created_at
                    - updated_at
                    properties:
                      id:
                        type: number
                      first_name:
                        type: string
                      last_name:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
  "/transactions":
    get:
      summary: list transactions
      tags:
      - Transactions
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                  - id
                  - to_account_id
                  - status
                  - transaction_type
                  - amount
                  - created_at
                  - updated_at
                  properties:
                    id:
                      type: number
                    from_account_id:
                      anyOf:
                      - type: number
                      - type: 'null'
                    to_account_id:
                      type: number
                    status:
                      type: string
                    transaction_type:
                      type: string
                    amount:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
    post:
      summary: create transaction
      tags:
      - Transactions
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - to_account_id
                - status
                - transaction_type
                - amount
                - created_at
                - updated_at
                properties:
                  id:
                    type: number
                  from_account_id:
                    anyOf:
                    - type: number
                    - type: 'null'
                  to_account_id:
                    type: number
                  status:
                    type: string
                  transaction_type:
                    type: string
                  amount:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction:
                  type: object
                  required:
                  - to_account_id
                  - amount
                  - transaction_type
                  properties:
                    from_account_id:
                      type: number
                    to_account_id:
                      type: number
                    amount:
                      type: string
                    transaction_type:
                      type: string
  "/transactions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show transaction
      tags:
      - Transactions
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - to_account_id
                - status
                - transaction_type
                - amount
                - created_at
                - updated_at
                properties:
                  id:
                    type: number
                  from_account_id:
                    anyOf:
                    - type: number
                    - type: 'null'
                  to_account_id:
                    type: number
                  status:
                    type: string
                  transaction_type:
                    type: string
                  amount:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
  "/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                  - id
                  - first_name
                  - last_name
                  - created_at
                  - updated_at
                  properties:
                    id:
                      type: number
                    first_name:
                      type: string
                    last_name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - first_name
                - last_name
                - created_at
                - updated_at
                properties:
                  id:
                    type: number
                  first_name:
                    type: string
                  last_name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  required:
                  - first_name
                  - last_name
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - first_name
                - last_name
                - created_at
                - updated_at
                properties:
                  id:
                    type: number
                  first_name:
                    type: string
                  last_name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
    patch:
      summary: update user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - first_name
                - last_name
                - created_at
                - updated_at
                properties:
                  id:
                    type: number
                  first_name:
                    type: string
                  last_name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  required:
                  - first_name
                  - last_name
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
    put:
      summary: update user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - id
                - first_name
                - last_name
                - created_at
                - updated_at
                properties:
                  id:
                    type: number
                  first_name:
                    type: string
                  last_name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  required:
                  - first_name
                  - last_name
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
    delete:
      summary: delete user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
